- name: "copy files from CircleCI to server"
  copy:
    src: /root/project/backend
    dest: /home/ubuntu

- name: "install package dependencies"
  shell: |
    cd /home/ubuntu/backend    
    npm install 

- name: "build package"
  shell: |
    cd /home/ubuntu/backend
    npm run build
    
- name: "use pm2 to run the node server"
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm -- run "start:dev"    